apiVersion: apps/v1 # La version va a cambiar depende del tipo de Recurso (En este caso Deployment)
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          #image: dressy/devops-backend:54d0ff2fcd73df8a091108fbce0b0b0952cc50df
          image: southamerica-west1-docker.pkg.dev/project-3467abaf-14aa-4dd9-ac1/devops-repo/backend:v1
          imagePullPolicy: Always
          #image: frontend:latest
          #imagePullPolicy: Never
          ports:
            - containerPort: 3001
