apiVersion: apps/v1 # La version va a cambiar depende del tipo de Recurso (En este caso Deployment)
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: dressy/devops-backend:0e20b759cb291903275e7cca9fdd6ffd7c90c771

          imagePullPolicy: Always
          #image: frontend:latest
          #imagePullPolicy: Never
          ports:
            - containerPort: 3001
