apiVersion: v1
kind: Service
metadata:
  name: backend-service # DNS interno del cluster

spec:
  selector:
    app: backend # Debe coincidir con el label del Deployment para que el Service sepa a qué Pods enviar el tráfico

  ports:
    - port: 3001 # Puerto en el que el Service estará disponible dentro del cluster
      targetPort: 3001 # Puerto en el que el contenedor del backend está escuchando

  type: ClusterIP # Accesible dentro del mismo cluster, no expuesto al exterior.