services:
  frontend: 
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3005:3005"        
    environment:
      - HOSTNAME=0.0.0.0
      - PORT=3005
    networks:
      - page_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    networks:
      - page_network

networks:
  page_network:
    driver: bridge