server {
    listen 80;
    server_name 34.176.23.110;

    location / {
        proxy_pass http://localhost:3005;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Opcional: Si tu frontend llama al backend por /api
    location /api/ {
        proxy_pass http://localhost:3006/;
    }
}