apiVersion: apps/v1 # La version va a cambiar depende del tipo de Recurso (En este caso Deployment)
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: dressy/devops-frontend:93c2669d4c44a7817409fe5a119b4cb6ca61e9f7
          
          #resources: # <--- ESTO ES LO QUE PERMITE EL ESCALADO DINÁMICO
            #requests:
              #cpu: "100m"
              #memory: "128Mi"
            #limits:
              #cpu: "200m"
              #memory: "256Mi"
          imagePullPolicy: Always
          #image: frontend:latest
          #imagePullPolicy: Never
          ports:
            - containerPort: 3000
