name: Build and Push Backend

on:
  push:
    branches: [ "main" ] # Se activa cuando subes a main
    paths:
      - 'backend/**' # Solo si cambias cosas en la carpeta backend
      - 'k8s/backend/**' # Se agregó por si se realizan cambios en los archivos de Kubernetes relacionados al backend

jobs:
  build:
    runs-on: ubuntu-latest #VM donde se ejecuta el job
    steps:
      - name: Checkout code # Clona el código del repo para que se pueda usar
        uses: actions/checkout@v4

      - name: Login to Docker Hub #Autenticacion con Docker Hub para poder subir la imagen
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend # Construye y empuja la imagen a Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          # .hash del commit como tag para que cada versión sea única
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-backend:${{ github.sha }}

      - name: Update Kubernetes resources
        run: |
          cd k8s/backend
          # Este sed es más agresivo: busca cualquier cosa que diga devops-backend y le pone el tag
          sed -i "s|image: .*devops-backend.*|image: dressy/devops-backend:${{ github.sha }}|g" deployment.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/backend/deployment.yaml
          # El "|| true" evita que el workflow falle si no hay cambios
          git commit -m "chore: update backend image to ${{ github.sha }}" || echo "No hay cambios nuevos"
          git pull --rebase origin main
          git push origin main || echo "Nada que empujar"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}